export type LenderTier =
  | "easy"
  | "volume"
  | "specialty"
  | "sba"
  | "loc"
  | "0pct"
  | "credit-union"
  | "construction";

export type MatchStatus = "COMPAT" | "POSSIBLE" | "NO";

export interface LenderCriteria {
  id: string;
  name: string;
  tier: LenderTier;
  submissionOrder: number;
  products: string[];
  minFicoBand: string | null;
  minTibMonths: number;
  maxPositions: number;
  excludedIndustries: string[];
  requiredIndustries: string[] | null;
  requiresRelationship: boolean;
  isActive: boolean;
  maxAmount: number | null;
  commissionPts: number | null;
  tracks: number[];
  notes: string;
  contactEmail?: string;
  contactPhone?: string;
}

export const LENDERS: LenderCriteria[] = [
  // ── 0% LOC — Submit FIRST ─────────────────────────────────────────────────
  {
    id: "7-figures-funding",
    name: "7 Figures Funding",
    tier: "0pct",
    submissionOrder: 1,
    products: ["0% revolving LOC", "personal term loan"],
    minFicoBand: "580-649",
    minTibMonths: 0,
    maxPositions: 99,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: 100000,
    commissionPts: null,
    tracks: [1, 2, 3],
    notes: "Zero inquiry damage. Submit here before anywhere else. 18-month 0% intro.",
    contactEmail: "partners@7figures.com",
    contactPhone: "833-801-5653",
  },

  // ── Easy MCA — Submit SECOND ──────────────────────────────────────────────
  {
    id: "lendini",
    name: "Lendini",
    tier: "easy",
    submissionOrder: 2,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 6,
    maxPositions: 3,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1, 2],
    notes: "Funds in 1–2 business days. All industries.",
    contactEmail: "submissions@lendini.com",
    contactPhone: "844-700-5363",
  },
  {
    id: "cfgms",
    name: "CFGMS",
    tier: "easy",
    submissionOrder: 3,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 4,
    maxPositions: 2,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: 9,
    tracks: [1, 2],
    notes: "4–7 months TIB. Factor rate 1.4s. 9 pts payout. All 50 states.",
    contactEmail: "pbalint@cfgms.com",
    contactPhone: "646-880-3819",
  },
  {
    id: "iou-financial",
    name: "IOU Financial",
    tier: "easy",
    submissionOrder: 4,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 6,
    maxPositions: 2,
    excludedIndustries: ["cannabis", "auto sales", "attorneys", "financial institutions"],
    requiredIndustries: [
      "grocery",
      "convenience",
      "food",
      "wholesale",
      "gas",
      "urgent care",
      "pharmacies",
      "vet",
      "animal",
      "liquor",
      "ups",
      "cleaning",
      "auto repair",
      "hvac",
      "landscaping",
      "paint",
      "plumbing",
      "trucking",
    ],
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: 10,
    tracks: [1, 2],
    notes:
      "A Paper MCA. 6–12 months. Max factor 1.32. Trucking requires 5+ trucks.",
    contactEmail: "jake@ioufinancial.com",
    contactPhone: "678-498-2400",
  },
  {
    id: "everest-business",
    name: "Everest Business Funding",
    tier: "easy",
    submissionOrder: 5,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 6,
    maxPositions: 2,
    excludedIndustries: [
      "financial institutions",
      "auto sales",
      "attorneys",
      "transportation",
    ],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: 15,
    tracks: [1, 2],
    notes: "Up to 15 pts. Up to 12 months.",
    contactEmail: "newdeals@ev-bf.com",
  },
  {
    id: "arf-financial",
    name: "ARF Financial",
    tier: "specialty",
    submissionOrder: 6,
    products: ["MCA", "LOC"],
    minFicoBand: null,
    minTibMonths: 12,
    maxPositions: 3,
    excludedIndustries: [],
    requiredIndustries: ["restaurant", "medical", "dental", "pharmacies"],
    requiresRelationship: false,
    isActive: true,
    maxAmount: 675000,
    commissionPts: 3,
    tracks: [1, 2],
    notes: "Restaurant + medical specialist. BLOC up to $675K. 3% initial + 3yr residuals.",
    contactEmail: "cdeal@arffinancial.com",
    contactPhone: "832-561-1424",
  },
  {
    id: "fintap",
    name: "Fintap",
    tier: "specialty",
    submissionOrder: 7,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 6,
    maxPositions: 3,
    excludedIndustries: [],
    requiredIndustries: ["cannabis", "trucking", "construction"],
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1, 2],
    notes: "The only easy MCA for cannabis, trucking, construction.",
    contactEmail: "awernick@fintap.com",
    contactPhone: "973-767-6552",
  },
  {
    id: "tmr",
    name: "TMR",
    tier: "easy",
    submissionOrder: 8,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 6,
    maxPositions: 2,
    excludedIndustries: ["construction", "trucking", "restaurants"],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: 10,
    tracks: [1, 2],
    notes: "3–12 months. Factor 1.2–1.5. No solo ISOs.",
    contactEmail: "uw@tmrnow.com",
    contactPhone: "212-220-9872",
  },

  // ── LOC Lenders ───────────────────────────────────────────────────────────
  {
    id: "bluevine",
    name: "BlueVine",
    tier: "loc",
    submissionOrder: 10,
    products: ["LOC", "term loan", "factoring"],
    minFicoBand: "650-699",
    minTibMonths: 12,
    maxPositions: 2,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: 250000,
    commissionPts: null,
    tracks: [1],
    notes: "Strong LOC option. Up to $250K.",
    contactEmail: "vincent.bitetto@bluevine.com",
    contactPhone: "650-252-1768",
  },
  {
    id: "greenbox-capital",
    name: "Greenbox Capital",
    tier: "loc",
    submissionOrder: 11,
    products: ["LOC", "MCA", "invoice factoring"],
    minFicoBand: "580-649",
    minTibMonths: 6,
    maxPositions: 3,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: 250000,
    commissionPts: 19,
    tracks: [1, 2],
    notes: "Up to 19% commission. All 50 states.",
    contactEmail: "info@greenboxcapital.com",
    contactPhone: "855-442-3423",
  },

  // ── Volume-Required MCA ───────────────────────────────────────────────────
  {
    id: "credibly",
    name: "Credibly",
    tier: "volume",
    submissionOrder: 20,
    products: ["MCA"],
    minFicoBand: "650-699",
    minTibMonths: 12,
    maxPositions: 2,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: true,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1],
    notes: "A Paper. Requires volume and online reputation.",
    contactEmail: "dhoff@credibly.com",
    contactPhone: "888-664-1444",
  },
  {
    id: "kapitus",
    name: "Kapitus",
    tier: "volume",
    submissionOrder: 21,
    products: ["MCA", "term loan"],
    minFicoBand: "650-699",
    minTibMonths: 12,
    maxPositions: 2,
    excludedIndustries: ["attorneys", "financial institutions"],
    requiredIndustries: null,
    requiresRelationship: true,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1],
    notes: "Requires relationship. Declines attorneys/financial institutions.",
    contactPhone: "800-780-7133",
  },
  {
    id: "ondeck",
    name: "OnDeck",
    tier: "volume",
    submissionOrder: 22,
    products: ["MCA", "LOC"],
    minFicoBand: "650-699",
    minTibMonths: 12,
    maxPositions: 2,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: true,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1],
    notes: "Requires relationship and volume.",
  },
  {
    id: "24-capital",
    name: "24 Capital",
    tier: "volume",
    submissionOrder: 23,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 6,
    maxPositions: 3,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: true,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1, 2],
    notes: "Requires volume relationship.",
  },

  // ── SBA / Term Loans — Submit LAST ────────────────────────────────────────
  {
    id: "smartbiz-loans",
    name: "SmartBizLoans",
    tier: "sba",
    submissionOrder: 30,
    products: ["SBA 7(a)"],
    minFicoBand: "680+",
    minTibMonths: 24,
    maxPositions: 1,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1],
    notes: "Best entry point for SBA. Handles packaging.",
    contactPhone: "1-866-283-8726",
  },
  {
    id: "funding-circle",
    name: "Funding Circle",
    tier: "sba",
    submissionOrder: 31,
    products: ["term loan"],
    minFicoBand: "650-699",
    minTibMonths: 24,
    maxPositions: 1,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1],
    notes: "2–5 year terms. Requires profitable tax returns.",
    contactPhone: "855-385-5356",
  },
  {
    id: "credibility-capital",
    name: "Credibility Capital",
    tier: "sba",
    submissionOrder: 32,
    products: ["term loan"],
    minFicoBand: "680+",
    minTibMonths: 24,
    maxPositions: 1,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: true,
    maxAmount: null,
    commissionPts: null,
    tracks: [1],
    notes: "2–3 year terms. Requires profitable tax returns.",
  },

  // ── PAUSED ────────────────────────────────────────────────────────────────
  {
    id: "forward-financing",
    name: "Forward Financing",
    tier: "easy",
    submissionOrder: 99,
    products: ["MCA"],
    minFicoBand: null,
    minTibMonths: 6,
    maxPositions: 99,
    excludedIndustries: [],
    requiredIndustries: null,
    requiresRelationship: false,
    isActive: false,
    maxAmount: null,
    commissionPts: null,
    tracks: [1, 2],
    notes: "PAUSED — partner onboarding suspended as of Aug 2026.",
  },
];
